user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'
cookie_file = './cookie.txt'

[thread]
enable = false
start_page = 1
max_error_count = 3

[reply]
enable = false
start_page = 1
max_error_count = 3

[followed_ba]
enable = false
start_page = 1
max_error_count = 3

[concern]
enable = true
start_page = 1
max_error_count = 3

[fan]
enable = false
start_page = 1
max_error_count = 3
